@startwbs ch2_wbs

skinparam Shadowing false
skinparam BackgroundColor #EFF1F3
skinparam linetype ortho

<style>
arrow {
    LineColor #323232
}
node {
    Padding 6
    Margin 2
    RoundCorner 15
    LineThickness 0.0
    BackgroundColor #EFF1F3
    FontColor #333333
}
.Type_Root {
    BackgroundColor #323232
    FontColor #FFFFFF
    LineColor #323232
}
.Type1_Node {
    BackgroundColor #D3548A
    FontColor #FFFFFF
    LineColor #D3548A
}
.Type1_LeafNode {
    RoundCorner 0
    LineThickness 1.0
    LineColor #D3548A
}
.Type2_Node {
    BackgroundColor #F4B031
    FontColor #FFFFFF
    LineColor #F4B031
}
.Type2_LeafNode {
    RoundCorner 0
    LineThickness 1.0
    LineColor #F4B031
}
.Type3_Node {
    BackgroundColor #BD4231
    FontColor #FFFFFF
    LineColor #BD4231
}
.Type3_LeafNode {
    RoundCorner 0
    LineThickness 1.0
    LineColor #BD4231
}
.Type4_Node {
    BackgroundColor #0F5E8C
    FontColor #FFFFFF
    LineColor #0F5E8C
}
.Type4_LeafNode {
    RoundCorner 0
    LineThickness 1.0
    LineColor #0F5E8C
}
.Type5_Node {
    BackgroundColor #37A7A8
    FontColor #FFFFFF
    LineColor #37A7A8
}
.Type5_LeafNode {
    RoundCorner 0
    LineThickness 1.0
    LineColor #37A7A8
}
</style>

* DDIA Chapter.2 - 資料模型與查詢語言<<Type_Root>>

** 關聯模型與文件模型<<Type1_Node>>

*** NoSQL 的誕生<<Type1_Node>>
**** 施工中
**** 施工中
**** 施工中

*** 關聯對象不匹配<<Type1_Node>>
**** 施工中
**** 施工中
**** 施工中

*** 多對一和多對多關係<<Type1_Node>>
**** 施工中
**** 施工中
**** 施工中

*** 文件資料庫是否在重蹈覆徹<<Type1_Node>>

**** 網路模型<<Type1_Node>>
***** 施工中
***** 施工中
***** 施工中

**** 關係模型<<Type1_Node>>
***** 施工中
***** 施工中
***** 施工中

**** 與文件資料庫相比<<Type1_Node>>
***** 施工中
***** 施工中
***** 施工中

*** 關聯資料庫與文件資料庫\n在今日的對比<<Type1_Node>>

**** 誰更有助於簡化程式碼
***** 施工中
***** 施工中
***** 施工中

**** 文件模型中的架構靈活性<<Type1_Node>>
***** 施工中
***** 施工中
***** 施工中

**** 查詢的資料局部性<<Type1_Node>>
***** 施工中
***** 施工中
***** 施工中

**** 文件和關聯資料庫的融合<<Type1_Node>>
***** 施工中
***** 施工中
***** 施工中

** 資料查詢語言<<Type2_Node>>

*** Web 上的聲明式查詢<<Type2_Node>>
**** 施工中
**** 施工中
**** 施工中

*** MapReduce 查詢<<Type2_Node>>
**** 施工中
**** 施工中
**** 施工中

** 圖模型<<Type3_Node>>

*** 屬性圖<<Type3_Node>>
**** 施工中
**** 施工中
**** 施工中

*** Cypher 查詢語言<<Type3_Node>>
**** 施工中
**** 施工中
**** 施工中

*** SQL 中的圖查詢<<Type3_Node>>
**** 施工中
**** 施工中
**** 施工中

*** 三元組儲存和 SPARQL<<Type3_Node>>
**** 施工中
**** 施工中
**** 施工中

**** 語義網路<<Type3_Node>>
***** 施工中
***** 施工中
***** 施工中

**** RDF 資料模型<<Type3_Node>>
***** 施工中
***** 施工中
***** 施工中

*** SPARQL 查詢語言<<Type3_Node>>
**** 施工中
**** 施工中
**** 施工中

**** 圖形資料庫與網路模型相比較<<Type3_Node>>
***** 施工中
***** 施工中
***** 施工中

*** Datalog<<Type3_Node>>
**** 施工中
**** 施工中
**** 施工中

@endwbs