@startmindmap ddia_mindmap_ch2

skinparam Shadowing false
skinparam BackgroundColor #EFF1F3

<style>
arrow {
    LineColor #0F5E8C
}
node {
    Padding 6
    Margin 0
    RoundCorner 15
    BackgroundColor #0F5E8C
    FontColor #FFFFFF
    LineThickness 0.0
}
leafNode {
    BackgroundColor #EFF1F3
    FontColor #333333
    LineThickness 0.0
}
.Description {
    BackgroundColor #EFF1F3
    FontColor #333333
    LineThickness 0.0
}
</style>

* DDIA Chapter 2 -\n資料模型與查詢語言

** 關聯模型與文件模型

*** NoSQL 的誕生
**** 施工中
**** 施工中
**** 施工中

*** 關聯對象不匹配
**** 施工中
**** 施工中
**** 施工中

*** 多對一和多對多關係
**** 施工中
**** 施工中
**** 施工中

*** 文件資料庫是否在重蹈覆徹

**** 網路模型
***** 施工中
***** 施工中
***** 施工中

**** 關係模型
***** 施工中
***** 施工中
***** 施工中

**** 與文件資料庫相比
***** 施工中
***** 施工中
***** 施工中

*** 關聯資料庫與文件資料庫\n在今日的對比

**** 誰更有助於簡化程式碼
***** 施工中
***** 施工中
***** 施工中

**** 文件模型中的架構靈活性
***** 施工中
***** 施工中
***** 施工中

**** 查詢的資料局部性
***** 施工中
***** 施工中
***** 施工中

**** 文件和關聯資料庫的融合
***** 施工中
***** 施工中
***** 施工中

left 

** 資料查詢語言

*** Web 上的聲明式查詢
**** 施工中
**** 施工中
**** 施工中

*** MapReduce 查詢
**** 施工中
**** 施工中
**** 施工中

** 圖模型

*** 屬性圖
**** 施工中
**** 施工中
**** 施工中

*** Cypher 查詢語言
**** 施工中
**** 施工中
**** 施工中

*** SQL 中的圖查詢
**** 施工中
**** 施工中
**** 施工中

*** 三元組儲存和 SPARQL
**** 施工中
**** 施工中
**** 施工中

**** 語義網路
***** 施工中
***** 施工中
***** 施工中

**** RDF 資料模型
***** 施工中
***** 施工中
***** 施工中

*** SPARQL 查詢語言
**** 施工中
**** 施工中
**** 施工中

**** 圖形資料庫與網路模型相比較
***** 施工中
***** 施工中
***** 施工中

*** Datalog
**** 施工中
**** 施工中
**** 施工中

@endmindmap